---
dist: bionic
sudo: false
language: ruby
rvm:
  - '2.7'
deploy:
  provider: rubygems
  api_key:
    secure: "qGOWCfn8zhZcCkRMdCVInya9/G9z7U8YksvxWr2HWjypFtgQ52nrhaHWVxvwSTJrM4pmACuhLeWxAkjI8jdBCpjBtDN4Iy2eIm1SqXM3W1AXVYjz+gNWirQh9dzfxvGmmsbKFNJU/jkyLqUijwbcP6ZNKecyBgoS1L73UnEvKlCg3KTtkHwWsftNrc8C5O6DOgN9o9kPMmwI++csodaejpHyMEDpw7gETuaiP1WPTBXArVhdZxhdTA6Edvoc9Cobi4KIIsJDNaRhknffbZlQxbMcgHpTLLt4StUWfoCmwcyxNNHcD/+RIQy2nUmn5jReUxywYNqU2xzH0JyrHoejbJNMPtP4ACFqnJaDzdqiEkEctEbhye/lNTEilXK/iDVkECfQe3V2nQ5UnuKsgSyeqWXUxGTnO/+viKi5jTQRIWZLI/ecb48XNdtRWkkWNAerXX8sJMI7Jx6zKw/vhezA2Fjk9g/JjcdxcGf+jB2ndcs+WOq7bCj7MLjdAUnxkD8Bz66KuzWH/xP6Ei1BUa2rg0kFFsRaBDjrE6SIhf1v2mXqXuQE8faxE4qYhHJvQjaGq2YzfasVAvfe5IonbPxEgHEYA3IcG8ToKewYHe7cFfp22Jwd2h6grDqBRdjCX9OS1xFACmULJl1SQw3am9yIGc8o+E3F7F8LqqvPSlE2fK0="
  gem: voxpupuli-test
  on:
    tags: true
    repo: voxpupuli/voxpupuli-test
    rvm: '2.7'

notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
